### ISSUE TITLE
[VL] Hive related unit tests fail

### ISSUE THREAD

**Issue by zhouyuan** [apache/incubator-gluten#11166]
### Backend

VL (Velox)

### Bug description

introduced in https://github.com/apache/incubator-gluten/pull/11154

it looks we should bump hive dependency for spark-4.0 
```
*** RUN ABORTED ***
  java.lang.NoClassDefFoundError: org/apache/hadoop/hive/llap/security/LlapSigner$Signable
  at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
  at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3373)
  at java.base/java.lang.Class.getConstructor0(Class.java:3578)
  at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2754)
  at org.apache.hive.common.util.ReflectionUtil.newInstance(ReflectionUtil.java:79)
  at org.apache.hadoop.hive.ql.exec.Registry.registerGenericUDTF(Registry.java:208)
  at org.apache.hadoop.hive.ql.exec.Registry.registerGenericUDTF(Registry.java:201)
  at org.apache.hadoop.hive.ql.exec.FunctionRegistry.<clinit>(FunctionRegistry.java:500)
  at org.apache.hadoop.hive.ql.plan.ExprNodeDescUtils.recommendInputName(ExprNodeDescUtils.java:174)
  at org.apache.hadoop.hive.ql.parse.SemanticAnalyzer.recommendName(SemanticAnalyzer.java:4550)
```

### Spark version

None

### Relevant logs

```bash

```
