### PR TITLE
[GLUTEN-8948][VL] Fallback iceberg delete from scan

### PR DESCRIPTION
**Pull request by jinchengchenghh**

### CODE REVIEW

**Review by FelixYBW — APPROVED** [review]

**Comment by zhztheplayer** [comment]
I just bumped into this PR.

There are two issues that I experienced:

1. The `GlutenTest...` tests are informal regarding junit's naming conventions, this could cause the tests not run in some cases. Naming them with `TestGluten` will solve the issue. I'll suggest double-checking whether the tests are actually being run in our CI.
2. The tests are under a package named `org.apache.gluten.spark34`, but the compilation is triggered for every Spark version. This makes compilation fail on other Spark versions. E.g., `-P spark-3.2,iceberg,backends-velox`
   ```
   /root/Work/code/incubator-gluten/backends-velox/src-iceberg/test/java/org/apache/gluten/spark34/extensions/GlutenTestMergeOnReadUpdate.java:19:26
   java: cannot find symbol
     symbol:   class PlanningMode
     location: package org.apache.iceberg
   ```

cc @jinchengchenghh see if you could take a look once available.

**Comment by jinchengchenghh** [comment]
1. I see a warning to suggest me to rename it to TestFluten xxx, but it can really run in intellij and CI. And iceberg tests also is this name format.
2. Is it because your local cache in your environment? I use this plugin to exclude the folder https://github.com/apache/incubator-gluten/pull/8800/files#diff-36079c5011e40a07a7f14e4c69f8391249da6ef9ad1098316bc7c0b77900fd5fR172, so it can pass the CI.

**Comment by zhztheplayer** [comment]
> And iceberg tests also is this name format.

If they start with `Test` then should be OK. Check this https://maven.apache.org/surefire/maven-surefire-plugin/examples/inclusion-exclusion.html.

I randomly pick a [log](https://productionresultssa10.blob.core.windows.net/actions-results/a40286e2-a80a-46c8-9622-c7b8031f4bc0/workflow-job-run-d40c65f5-8665-5d5c-bd0c-568fd9567268/logs/job/job-logs.txt?rsct=text%2Fplain&se=2025-06-09T07%3A10%3A40Z&sig=LSEWykIWiXDyHideGgFQHcGuYQpUR5sC0BBPDitGCNM%3D&ske=2025-06-09T16%3A28%3A12Z&skoid=ca7593d4-ee42-46cd-af88-8b886a2f84eb&sks=b&skt=2025-06-09T04%3A28%3A12Z&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skv=2025-05-05&sp=r&spr=https&sr=b&st=2025-06-09T07%3A00%3A35Z&sv=2025-05-05) and they haven't appeared to run, could you share a log showing the tests are runnable?

> Is it because your local cache in your environment? 

Not sure but both of my two machines encountered the same in IDEA. Are you able to work with iceberg + 3.3 with Intellij IDEA compiler?

**Comment by jinchengchenghh** [comment]
1. Yes, you are right, Intellij can run the test, I create a PR to try to fail the test in ci https://github.com/apache/incubator-gluten/pull/9923, but succeed, I will create a new PR to rename the test.

2. I usually compile with spark-3.4, I try spark-3.3 before, compilation failed within intellij, do you have any suggestion?
