### PR TITLE
[GLUTEN-9291][VL] Fix Spark try_cast and cast function error case handling

### PR DESCRIPTION
**Pull request by zhli1142015**
## What changes were proposed in this pull request?

(Please fill in changes proposed in this fix)

Fixes: #9291

Depends on https://github.com/facebookincubator/velox/pull/12993

## How was this patch tested?
UT.

### CODE REVIEW

**Comment by philo-he** [comment]
@zhli1142015, just reopened this pr, assuming it is still necessary.

**Comment by zhli1142015** [comment]
Yes, thank you, I'm still waiting the velox PR to be merged. 
https://github.com/facebookincubator/velox/pull/12993

**Comment by FelixYBW** [comment]
@zhli1142015 can you solve conflict? We need to merge this PR for today's rebase.

FYI, @zhouyuan

**Comment by FelixYBW** [comment]
build failure after https://github.com/facebookincubator/velox/pull/12993 imported
```
17:42:37  1251.2 /incubator-gluten/cpp/velox/substrait/VeloxToSubstraitExpr.cc: In member function 'const substrait::Expression_Cast& gluten::VeloxToSubstraitExprConvertor::toSubstraitExpr(google::protobuf::Arena&, const std::shared_ptr<const facebook::velox::core::CastTypedExpr>&, const RowTypePtr&)':
17:42:37  1251.2 /incubator-gluten/cpp/velox/substrait/VeloxToSubstraitExpr.cc:383:17: error: 'using element_type = const class facebook::velox::core::CastTypedExpr' {aka 'const class facebook::velox::core::CastTypedExpr'} has no member named 'nullOnFailure'
17:42:37  1251.2   383 |   if (castExpr->nullOnFailure()) {
17:42:37  1251.2       |                 ^~~~~~~~~~~~~
17:42:37  1251.2 make[2]: *** [velox/CMakeFiles/velox.dir/build.make:538: velox/CMakeFiles/velox.dir/substrait/VeloxToSubstraitExpr.cc.o] Error 1
17:42:37  1251.2 make[2]: *** Waiting for unfinished jobs....
17:42:37  1261.8 make[1]: *** [CMakeFiles/Makefile2:170: velox/CMakeFiles/velox.dir/all] Error 2
17:42:37  1261.8 make: *** [Makefile:136: all] Error 2
```

**Comment by zhli1142015** [comment]
Updated, but I thought we need to apply velox change with this same time.

File: ep/build-velox/src/get_velox.sh [hunk 1]
```diff
@@ -17,7 +17,7 @@
 set -exu
 
 VELOX_REPO=https://github.com/oap-project/velox.git
-VELOX_BRANCH=2025_06_23
+VELOX_BRANCH=2025_06_24
```
Comment (zhouyuan) [inline ep/build-velox/src/get_velox.sh:20]: can you help to bump the `VELOX_ENHANCED_REPO` also?
